package com.otasdk

import org.junit.Assert.*
import org.junit.Assume
import org.junit.Test
import java.io.File

/**
 * Verifies the Kotlin bspatch against patches the server actually produced.
 *
 * The fixtures in tests/fixtures/ are generated by the TypeScript bsdiff
 * implementation (see packages/backend/src/utils/bsdiff.ts). Testing against
 * real server output — rather than a Kotlin-side re-implementation — is the
 * only way to catch the ports disagreeing about the wire format, which is
 * exactly where a bug would silently corrupt a bundle on device.
 *
 * Regenerate with the fixture-generation test in the backend package.
 */
class BsPatchTest {

    private fun fixtureDir(): File? {
        // The working directory depends on how Gradle resolved this module —
        // directly, or through autolinking from a consuming app's node_modules.
        // Walk up from wherever we started until tests/fixtures turns up.
        var dir: File? = File(".").canonicalFile
        repeat(6) {
            val candidate = File(dir, "tests/fixtures")
            if (candidate.isDirectory && File(candidate, "index.json").exists()) {
                return candidate
            }
            dir = dir?.parentFile
        }
        return null
    }

    private fun load(name: String): Triple<ByteArray, ByteArray, ByteArray> {
        val dir = fixtureDir()!!
        return Triple(
            File(dir, "$name.old").readBytes(),
            File(dir, "$name.new").readBytes(),
            File(dir, "$name.patch").readBytes(),
        )
    }

    private fun assertFixtureApplies(name: String) {
        val dir = fixtureDir()
        Assume.assumeTrue(
            "Fixtures not found — run the backend fixture generator first",
            dir != null,
        )

        val (old, expected, patch) = load(name)
        val result = BsPatch.apply(old, patch)
        assertArrayEquals("Fixture \"$name\" did not reconstruct correctly", expected, result)
    }

    @Test
    fun `applies a real bundle patch`() = assertFixtureApplies("bundle")

    @Test
    fun `handles an empty base`() = assertFixtureApplies("emptyOld")

    @Test
    fun `handles an empty target`() = assertFixtureApplies("emptyNew")

    @Test
    fun `handles identical files`() = assertFixtureApplies("identical")

    @Test
    fun `handles high bytes and wraparound arithmetic`() = assertFixtureApplies("highBytes")

    @Test
    fun `handles negative seek offsets`() {
        // Sign-magnitude encoding is not two's complement. Reading these as a
        // normal signed long produces a wrong — but plausible — result, so this
        // case is worth pinning down on its own.
        assertFixtureApplies("negativeSeek")
    }

    @Test
    fun `patch is dramatically smaller than the bundle`() {
        val dir = fixtureDir()
        Assume.assumeTrue(dir != null)

        val (old, _, patch) = load("bundle")
        assertTrue(
            "Patch (${patch.size}B) should be a tiny fraction of the bundle (${old.size}B)",
            patch.size < old.size / 100,
        )
    }

    // ── Rejection of malformed input ────────────────────────────────

    @Test(expected = BsPatch.PatchFormatException::class)
    fun `rejects a patch shorter than its header`() {
        BsPatch.apply(ByteArray(100), ByteArray(10))
    }

    @Test(expected = BsPatch.PatchFormatException::class)
    fun `rejects a bad magic header`() {
        val patch = ByteArray(64)
        "NOTBSDIF".toByteArray(Charsets.US_ASCII).copyInto(patch)
        BsPatch.apply(ByteArray(100), patch)
    }

    @Test
    fun `rejects a truncated patch`() {
        val dir = fixtureDir()
        Assume.assumeTrue(dir != null)

        val (old, _, patch) = load("bundle")
        val truncated = patch.copyOf(patch.size - 50)

        try {
            BsPatch.apply(old, truncated)
            fail("Expected a PatchFormatException for a truncated patch")
        } catch (e: BsPatch.PatchFormatException) {
            // expected
        }
    }

    @Test
    fun `does not silently produce the right answer from the wrong base`() {
        val dir = fixtureDir()
        Assume.assumeTrue(dir != null)

        val (_, expected, patch) = load("bundle")
        val wrongBase = ByteArray(200_000) { (it * 13).toByte() }

        try {
            val result = BsPatch.apply(wrongBase, patch)
            // If it did not throw, the output must not match the target. The
            // per-file hash check in BundleManager is what catches this.
            assertFalse(expected.contentEquals(result))
        } catch (e: BsPatch.PatchFormatException) {
            // Also acceptable.
        }
    }
}
