#import <React/RCTBridgeModule.h>
#import <React/RCTEventEmitter.h>

// ObjC bridge — auto-generated by create-react-native-library.
// Maps Swift class OtaSdk → JS module "OtaSdk".
// Do not add logic here — all code lives in OtaSdk.swift.

@interface RCT_EXTERN_MODULE(OtaSdk, RCTEventEmitter)

RCT_EXTERN_METHOD(configure:(NSDictionary *)config)

RCT_EXTERN_METHOD(checkForUpdate:
                  (RCTPromiseResolveBlock)resolve
                  rejecter:(RCTPromiseRejectBlock)reject)

RCT_EXTERN_METHOD(downloadBundle:(NSString *)bundleId
                  downloadUrl:(NSString *)downloadUrl
                  expectedHash:(NSString *)expectedHash
                  options:(NSDictionary *)options
                  resolver:(RCTPromiseResolveBlock)resolve
                  rejecter:(RCTPromiseRejectBlock)reject)

RCT_EXTERN_METHOD(applyPendingBundle:
                  (RCTPromiseResolveBlock)resolve
                  rejecter:(RCTPromiseRejectBlock)reject)

RCT_EXTERN_METHOD(getStatus:
                  (RCTPromiseResolveBlock)resolve
                  rejecter:(RCTPromiseRejectBlock)reject)

RCT_EXTERN_METHOD(markStable)

RCT_EXTERN_METHOD(rollback:
                  (RCTPromiseResolveBlock)resolve
                  rejecter:(RCTPromiseRejectBlock)reject)

@end
